### ISSUE TITLE
Kill-switch broken?

### ISSUE THREAD

**Issue by neerdoc** [faanskit/ha-checkwatt#79]
I understand that the kill-switch is a way to protect checkwatt's servers, which is great, as stated in #69. I have the same issue as #78 though, and checking the https://checkwatt.se/ha-killswitch.txt link, it returns a php-page. Not a 1 or a 0. Can checkwatt accidentally have broken it? And is it individual or the same for all of us using ha-checkwatt?

**Comment by faanskit** [comment]
Kill-switch is generic, happens before login. If file is absent or content is 1, pyCheckwatt stops.
The fix for this is to remove check for killswitch and release pyCheckwatt and hs-checkwatt. 
https://github.com/faanskit/pyCheckwatt/blob/f874a99429a4f1efd784652008e4d962a5ddcc39/pycheckwatt/__init__.py#L230

Or...contact Checkwatt to ask them to bring the file back

**Comment by faanskit** [comment]
Checkwatt confirmed thet removed it by mistake last week. They will re-insert it.
